### ISSUE TITLE
Voting seems to be broken

### ISSUE THREAD

**Issue by 94726** [LeoTuet/backend-we-want-to-sleep#75]
### Operating system

Windows 11

### Browser

Chrome

### Urgency of your Issue

Medium

### Bug description

When voting, it responds with a Server Error.

### Steps to reproduce

Go to https://wewanttosleep.de/%Token%
open network tab
do captcha
do vote

see error

### Relevant log output

![image](https://user-images.githubusercontent.com/58269084/174494632-f3d23174-3e2e-4b36-9f2e-2a1c8381d893.png)

**Comment by 94726** [comment]
```shell
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    | > backend-we-want-to-sleep@0.0.0 start /app
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    | > node ./dist
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    | [2022-06-19T18:14:21.573Z] INFO: Express server started on port: 3000
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    | Connected to database!
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    | MongoServerError: E11000 duplicate key error collection: wwts.vote index: token_1_ballot_1 dup key: { token: null, ballot: null }
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |     at /app/node_modules/mongodb/lib/operations/insert.js:51:33
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |     at /app/node_modules/mongodb/lib/cmap/connection_pool.js:273:25
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |     at handleOperationResult (/app/node_modules/mongodb/lib/sdam/server.js:363:9)
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |     at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:474:9)
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |     at MessageStream.emit (events.js:400:28)
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |     at writeOrBuffer (internal/streams/writable.js:358:12)
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |     at Socket.ondata (internal/streams/readable.js:731:22) {
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |   index: 0,
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |   code: 11000,
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |   keyPattern: { token: 1, ballot: 1 },
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    |   keyValue: { token: null, ballot: null }
wwts-cluster_wwts_api.1.py3ivz56h36h@ubuntu-wwts    | }
```

**Comment by LeoTuet** [comment]
Indexes of voting where deprecated. Dropped them manually.
